### ISSUE TITLE
ReadLine's history_file should expand '~' to $ENV{HOME}

### ISSUE THREAD

**Issue by y** [doy/reply#48]
The history_file option for Plugin::ReadLine should expand a leading '~' to allow users to specify the file at the top-level of their home directory. Example: history_file = '~/.reply_history'

**Comment by doy** [comment]
Fixed in e015c5c (although `history_file = .reply_history` has always worked).

**Comment by y** [comment]
> Fixed in e015c5c (although history_file = .reply_history has always worked).

The update doesn't work for me. I am using 0.39 with Perl 5.24.0 and am still getting the same error:

    1> exit
    Couldn't write history to /Users/y/Library/Application Support/'~/.reply_history' at /perlbrew/perls/perl-5.2.4/lib/site_perl/5.24.0/Reply/Plugin/ReadLine.pm line 81.

It turns out quoted paths are not handled properly, even though your example in the pod quotes the path.
So this works: `history_file = ~/.reply_history`
This doesn't: `history_file = '~/.reply_history'`
If you use `$history = glob($history);` instead of `$history =~ s{^~/}{$ENV{HOME}/};` it will properly deal with the quotes, though it might be better dealing with them at the config reader level.

And `history_file = .reply_history` doesn't write to where I want because that's considered a relative pathname, so it writes to File::HomeDir->my_**data**, but I want it to write to File::HomeDir->my_**home**.
